services:
  mysql :
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=ps-projekt'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=password'
    ports:
      - '3307:3306'